export enum WorkerErrorResponseAction {
    UNKNOWN_ACTION = 'WORKER/UNKNOWN_ACTION',
    ERROR = 'WORKER/ERROR',
    ERROR_DURING_INIT = 'WORKER/ERROR_DURING_INIT',
    ERROR_UNKNOWN_PACKET = 'WORKER/ERROR/UNKNOWN_PACKET',
}
