name: PR Check

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [ main ]

  workflow_dispatch:

jobs:
  pr_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - uses: c-hive/gha-yarn-cache@v2
      
      - name: Install node modules
        run: |
          yarn install --frozen-lockfile
          
      - name: Run linting
        run: yarn lint

      - name: Run tests
        run: yarn test
        
      - name: Run dev build
        run: yarn build
        
